version: "3.9"

services:
  app:
    build: .
    image: dubich/app
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    restart: always
    depends_on:
      - postgres
    networks:
      - net
    volumes:
      - ./logs:/app/logs:rw
  postgres:
    build: ./db
    image: dubich/postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PGDATA=: ${PGDATA}
    volumes:
      - ./db:/var/lib/postgresql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    networks:
      - net
networks:
  net:
    name: custom_network
    driver: bridge