version: "3.9"

services:
  postgres:
    build: .
    image: dubich/postgres
    container_name: db_container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PGDATA: ${PGDATA}
    volumes:
      - db:/var/lib/postgresql/data:rw
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
volumes:
  db: